spring: 
  application: 
    name: chat
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /static/**


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://15.164.129.107:3306/service?serverTimezone=UTC&characterEncoding=UTF-8
    username: guney
    password: "!sotusjf0"
    
  session:
    jdbc:
      initialize-schema: always

# -- Server Port
server: 
  port: 9000
  
  #jsp 자동빌드
  servlet:
    jsp:
      init-parameters:
        development: true 
        
mybatis: 
  mapper-locations: classpath:mapper/**/*.xml